# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CropExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CropExample
 pod 'SnapKit'

  target 'CropExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CropExampleUITests' do
    # Pods for testing
  end

end
